apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeappdeployment
  labels:
    type: backend
    app: nodeapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      type: backend
      app: nodeapp
  template:
    metadata:
      labels:
        type: backend
        app: nodeapp
    spec:
      containers:
      - name: nodeappcontainer
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: {{ .Values.service.port }}