apiVersion: v1
kind: Service
metadata:
  name: nodeapp-load-balancer-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '80'
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    type: backend
    app: nodeapp
