apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeappdeployment
  labels:
    type: backend
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      type: backend
      app: nodeapp
  template:
    metadata:
      name: nodeapp
      labels:
        type: backend
        app: nodeapp
    spec:
      containers:
      - name: nodeappcontainer
        image: us.gcr.io/eventos1001/nodeapp:v1
        ports:
          - containerPort: 80