apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nodeapp-monitor
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      type: backend
      app: nodeapp
  endpoints:
  - port: web
